// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzkcajztqkqzbtwzenpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6a2Nhanp0cWtxemJ0d3plbnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjU0OTcsImV4cCI6MjA2NzcwMTQ5N30.nJmepRuoqd_M8PpSNiujj_yYHQP1bZpselKeFdoiLmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});